channel:
  id: 2007065821
  secret: c71182056769aa213388cf55ce2c1a5d
  accessToken: >-
    l55CqfZ/JiIKvSkF0TTdRcmOrPTw/cDVtuxVt0QezuSnWJ+bmHU7elhaGxlGdHA+m4QO7U7FMDu8gr6k/5+M3E9XF/LDx1VTLlh3CDoD/noFsyRxA0qwjEb4IvwbfzOTpv2lPGIRrmz43KuDOs9kTY9PbdgDzCFqoOLOYbqAITQ=
